/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO192M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFRO192M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFRO192M_CORE_CLOCK          96000000U  /*!< Core clock frequency: 96000000Hz */

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFRO192M_ADC0_CLOCK             0UL            /* Clock consumers of ADC0_clock output : ADC0 */
#define BOARD_BOOTCLOCKFRO192M_CLK16K_0_CLOCK         0UL            /* Clock consumers of CLK16K_0_clock output : CMP0, WAKETIMER0, WUU0 */
#define BOARD_BOOTCLOCKFRO192M_CLK16K_1_CLOCK         0UL            /* Clock consumers of CLK16K_1_clock output : CMP1, LPTMR0, WAKETIMER0 */
#define BOARD_BOOTCLOCKFRO192M_CLKOUT_CLOCK           0UL            /* Clock consumers of CLKOUT_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_CLK_1M_CLOCK           1000000UL      /* Clock consumers of CLK_1M_clock output : CMC */
#define BOARD_BOOTCLOCKFRO192M_CLK_48M_CLOCK          48000000UL     /* Clock consumers of CLK_48M_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_CLK_IN_CLOCK           0UL            /* Clock consumers of CLK_IN_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_CMP0FDIV_CLOCK         0UL            /* Clock consumers of CMP0FDIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFRO192M_CMP0RRDIV_CLOCK        0UL            /* Clock consumers of CMP0RRDIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFRO192M_CMP1FDIV_CLOCK         0UL            /* Clock consumers of CMP1FDIV_clock output : CMP1 */
#define BOARD_BOOTCLOCKFRO192M_CMP1RRDIV_CLOCK        0UL            /* Clock consumers of CMP1RRDIV_clock output : CMP1 */
#define BOARD_BOOTCLOCKFRO192M_CPU_CLOCK              96000000UL     /* Clock consumers of CPU_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_CTIMER0_CLOCK          0UL            /* Clock consumers of CTIMER0_clock output : CTIMER0 */
#define BOARD_BOOTCLOCKFRO192M_CTIMER1_CLOCK          0UL            /* Clock consumers of CTIMER1_clock output : CTIMER1 */
#define BOARD_BOOTCLOCKFRO192M_CTIMER2_CLOCK          0UL            /* Clock consumers of CTIMER2_clock output : CTIMER2 */
#define BOARD_BOOTCLOCKFRO192M_FREQME_REFERENCE_CLOCK 12000000UL     /* Clock consumers of FREQME_reference_clock output : FREQME0 */
#define BOARD_BOOTCLOCKFRO192M_FREQME_TARGET_CLOCK    12000000UL     /* Clock consumers of FREQME_target_clock output : FREQME0 */
#define BOARD_BOOTCLOCKFRO192M_FRO_12M_CLOCK          12000000UL     /* Clock consumers of FRO_12M_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_FRO_HF_DIV_CLOCK       96000000UL     /* Clock consumers of FRO_HF_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_FRO_HF_CLOCK           192000000UL    /* Clock consumers of FRO_HF_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_I3C_FCLK_CLOCK         0UL            /* Clock consumers of I3C_FCLK_clock output : I3C0 */
#define BOARD_BOOTCLOCKFRO192M_I3C_SLOW_TC_CLOCK      0UL            /* Clock consumers of I3C_SLOW_TC_clock output : I3C0 */
#define BOARD_BOOTCLOCKFRO192M_I3C_SLOW_CLOCK         0UL            /* Clock consumers of I3C_SLOW_clock output : I3C0 */
#define BOARD_BOOTCLOCKFRO192M_LPI2C0_CLOCK           0UL            /* Clock consumers of LPI2C0_clock output : LPI2C0 */
#define BOARD_BOOTCLOCKFRO192M_LPSPI0_CLOCK           0UL            /* Clock consumers of LPSPI0_clock output : LPSPI0 */
#define BOARD_BOOTCLOCKFRO192M_LPSPI1_CLOCK           0UL            /* Clock consumers of LPSPI1_clock output : LPSPI1 */
#define BOARD_BOOTCLOCKFRO192M_LPTMR0_CLOCK           0UL            /* Clock consumers of LPTMR0_clock output : LPTMR0 */
#define BOARD_BOOTCLOCKFRO192M_LPUART0_CLOCK          0UL            /* Clock consumers of LPUART0_clock output : LPUART0 */
#define BOARD_BOOTCLOCKFRO192M_LPUART1_CLOCK          0UL            /* Clock consumers of LPUART1_clock output : LPUART1 */
#define BOARD_BOOTCLOCKFRO192M_LPUART2_CLOCK          0UL            /* Clock consumers of LPUART2_clock output : LPUART2 */
#define BOARD_BOOTCLOCKFRO192M_MAIN_CLOCK             192000000UL    /* Clock consumers of MAIN_clock output : FLEXPWM0 */
#define BOARD_BOOTCLOCKFRO192M_OSTIMER_CLOCK          1000000UL      /* Clock consumers of OSTIMER_clock output : OSTIMER0 */
#define BOARD_BOOTCLOCKFRO192M_FIRC_TRIM_CLOCK        0UL            /* Clock consumers of SCG.FIRC_TRIM_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_SIRC_TRIM_CLOCK        0UL            /* Clock consumers of SCG.SIRC_TRIM_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_SYSTICK_CLOCK          0UL            /* Clock consumers of SYSTICK_clock output : SysTick */
#define BOARD_BOOTCLOCKFRO192M_SLOW_CLOCK             24000000UL     /* Clock consumers of Slow_clock output : AOI0, CMC, CMP0, LPTMR0, WUU0 */
#define BOARD_BOOTCLOCKFRO192M_SYSTEM_CLOCK           96000000UL     /* Clock consumers of System_clock output : ADC0, CMP1, CTIMER0, CTIMER1, CTIMER2, DMA0, FLEXPWM0, FREQME0, GPIO0, GPIO1, GPIO2, GPIO3, I3C0, INPUTMUX0, LPI2C0, LPSPI0, LPSPI1, LPUART0, LPUART1, LPUART2, OSTIMER0, PORT0, PORT1, PORT2, PORT3, QDC0, SWD, SysTick, USB0, UTICK0, WWDT0 */
#define BOARD_BOOTCLOCKFRO192M_TRACE_CLOCK            96000000UL     /* Clock consumers of TRACE_clock output : SWD */
#define BOARD_BOOTCLOCKFRO192M_USB0_CLOCK             0UL            /* Clock consumers of USB0_clock output : USB0 */
#define BOARD_BOOTCLOCKFRO192M_UTICK_CLOCK            1000000UL      /* Clock consumers of UTICK_clock output : UTICK0 */
#define BOARD_BOOTCLOCKFRO192M_WUU_CLOCK              0UL            /* Clock consumers of WUU_clock output : N/A */
#define BOARD_BOOTCLOCKFRO192M_WWDT0_CLOCK            1000000UL      /* Clock consumers of WWDT0_clock output : WWDT0 */


/*******************************************************************************
 * API for BOARD_BootClockFRO192M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFRO192M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

