/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUART(void);

#define PCR_IBE_ibe0 0x00u         /*!<@brief Input Buffer Enable: Disables */
#define PORT2_PCR1_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT3_PCR7_MUX_mux101 0x05u /*!<@brief Pin Multiplex Control: Alternative 5 (chip-specific) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_13 (number 37), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLED_LED_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLED_LED_GREEN_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLED_LED_GREEN_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITLED_LED_GREEN_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLED_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLED_LED_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITLED_LED_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_12 (number 38), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLED_LED_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLED_LED_RED_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLED_LED_RED_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITLED_LED_RED_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLED_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLED_LED_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITLED_LED_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT3_0 (number 46), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLED_LED_BLUE_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLED_LED_BLUE_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITLED_LED_BLUE_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITLED_LED_BLUE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLED_LED_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLED_LED_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITLED_LED_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLED(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT3_PCR29_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_7 (number 1), SW
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTON_SW3_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTON_SW3_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTON_SW3_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTON_SW3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTON_SW3_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTON_SW3_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_29 (number 32), SW
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTON_SW2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTON_SW2_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTON_SW2_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTON_SW2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTON_SW2_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTON_SW2_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTON(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
